// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebApi.Infrastructure;

#nullable disable

namespace SimpleWebApi.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20240228134001_addcloumn")]
    partial class addcloumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SimpleWebApi.Infrastructure.Entities.AlarmManagement.AlarmManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GuardPaneDisplayAlarm")
                        .HasColumnType("int");

                    b.Property<int>("GuardPaneLineBodyAlarm")
                        .HasColumnType("int");

                    b.Property<int>("GuardPanelSoundAndLightAlarm")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否删除");

                    b.Property<int>("NameplateDisplayAlarm")
                        .HasColumnType("int");

                    b.Property<int>("NameplateLineBodyAlarm")
                        .HasColumnType("int");

                    b.Property<int>("NameplateSoundAndLightAlarm")
                        .HasColumnType("int");

                    b.Property<int>("VehicleDisplay")
                        .HasColumnType("int");

                    b.Property<int>("VehicleLineBody")
                        .HasColumnType("int");

                    b.Property<int>("VehicleSoundAndLight")
                        .HasColumnType("int");

                    b.Property<int>("VinDisplayAlarm")
                        .HasColumnType("int");

                    b.Property<int>("VinLineBodyAlarm")
                        .HasColumnType("int");

                    b.Property<int>("VinSoundAndLightAlarm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlarmManagement");
                });

            modelBuilder.Entity("SimpleWebApi.Infrastructure.Entities.Test.TestDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否删除");

                    b.Property<string>("TestDate")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TestDb");
                });

            modelBuilder.Entity("SimpleWebApi.Infrastructure.Entities.VehicleInspection.VehicleInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("InspectionItem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InspectionLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("InspectionStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InspectionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2024, 2, 28, 21, 40, 1, 127, DateTimeKind.Local).AddTicks(2485));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("是否删除");

                    b.Property<string>("Vin")
                        .HasColumnType("longtext")
                        .HasComment("Vin");

                    b.HasKey("Id");

                    b.ToTable("VehicleInspection");
                });
#pragma warning restore 612, 618
        }
    }
}
